language: python
python:
  - 3.4
  - 3.5
  - 3.6

sudo: false

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install -e .[test]

script:
  - flake8 .
  - mypy --ignore-missing-imports parsely
  - py.test tests.py --cov=parsely --cov-report term-missing
  - rst2html.py README.rst --exit-status=2 > /dev/null
  - rst2html.py CHANGELOG.rst --exit-status=2 > /dev/null
